name: Build and Release Sursface

on:
  push:
    branches:
      - main

jobs:
  initialize_release:
    name: Initialize GitHub Release
    runs-on: ubuntu-latest

    outputs:
      release_id: ${{ steps.create_release.outputs.id }}
      tag_name: ${{ steps.generate_tag.outputs.tag }}

    steps:
      - name: Generate Tag Name
        id: generate_tag
        run: |
          TAG_NAME="v$(date +'%Y%m%d%H%M%S')"
          echo "TAG_NAME=$TAG_NAME" >> $GITHUB_ENV
          echo "::set-output name=tag::$TAG_NAME"

      - name: Create Empty Release
        id: create_release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ steps.generate_tag.outputs.tag }}
          token: ${{ secrets.GITHUB_TOKEN }}
          draft: false
          prerelease: false

  build:
    name: Build Binaries
    runs-on: ubuntu-latest
    needs: initialize_release
    
    strategy:
      matrix:
        target: [
          "x86_64-linux"
        ]

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Setup Nix
        uses: cachix/install-nix-action@v21
        with:
          nix_path: nixpkgs=channel=nixos-24.05

      - name: Build Package
        run: |
          nix build .#${{ matrix.target }}
          mkdir -p output
          zip -r output/qass-${{ matrix.target }}.zip result/*

      - name: Upload Release Asset
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ needs.initialize_release.outputs.tag_name }}
          files: output/qass-${{ matrix.target }}.zip
          token: ${{ secrets.GITHUB_TOKEN }}